# Generated by Django 4.0.4 on 2024-05-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_job_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
    ]
