# Generated by Django 4.0.4 on 2024-05-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(to='Company.category'),
        ),
    ]
