# Generated by Django 4.0.4 on 2024-05-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_job_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
