# Generated by Django 4.0.4 on 2024-05-15 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobHunter', '0006_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='availability_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='position_applied',
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('can_contact', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='JobHunter.application')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_work', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='JobHunter.application')),
            ],
        ),
    ]
