# Generated by Django 4.0.4 on 2024-05-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobHunter', '0007_remove_application_availability_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(default='Reykjavik', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default='Iceland', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
