# Generated by Django 4.0.4 on 2024-05-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHunter', '0008_remove_application_notes_remove_application_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
    ]
