# Generated by Django 4.0.4 on 2024-05-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobHunter', '0011_alter_application_job'),
        ('JobHunter', '0011_profile_city'),
    ]

    operations = [
    ]
